media: 'assets/uploads'
content:
  - name: posts
    label: 'Posts'
    type: collection
    icon: file-stack
    path: '_posts'
    # by default filename saved in format {year}-{month}-{day}-{primary}.md.
    # config below saved for reference later.
    #filename: '{year}-{month}-{day}-{primary}.md'
    view:
      primary: title
      fields: [ title, date, published ]
      sort: [ published, date, title ]
      default:
        search: ''
        sort: published
        order: asc
    fields:
      - name: title
        label: 'Title'
        type: string
      - name: published
        label: 'Publish'
        type: boolean
        default: false
      - name: date
        label: 'Date Published'
        type: date
      - name: image
        label: Cover Image
        type: image
      - name: body
        label: 'Content'
        type: code
        options:
          language: markdown

  - name: readme
    label: About me
    path: README.md
    type: file
    icon: circle-user-round
    fields:
      - name: title
        label: 'Title'
        type: string
      - name: body
        label: 'Content'
        type: code
        options:
          language: markdown

  - name: config
    label: Jekyll config
    path: _config.yml
    type: file
    icon: settings
