sudo: false
language: ruby

# https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/
cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer #https://github.com/gjtorikian/html-proofer/issues/381

rvm:
  -  2.5.7

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors on html-proofer

notifications:
  email: false

script:
  - make
