# Ref:
#
# https://help.github.com/articles/configuring-jekyll/
# https://jekyllrb.com/docs/configuration/

# used on kontak page to send email through formspree
email: maywlrba

remote_theme: jekyll/minima@5f61d94
minima:
  date_format: '%d-%m-%Y'
  skin: auto
  nav_pages:
    - README.md
    - contact.html
    - privacy-policy.md
  hide_site_feed_link: true
  
# used by minima (to render author name and email in footer)
# jekyll-seo-tag for something (I dont remember)
author:
  name: Akhyar RH
  #email: "akhyarrh@gmail.com"
  # https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#setting-author-url
  url: 'https://twitter.com/akhyarrh'  
  
# ignore minima's default config
# expect chaos
ignore_theme_config: true

timezone: Asia/Makassar

title: "AkhyarRH's Weblog"
tagline: &desc Level 30. Male. Human.
description: *desc
url: &url 'https://akhyar.id'
repository: akhyarrh/akhyarrh.github.io

# Staticman url
#staticman_url: 'https://staticman-akhyarrh.netlify.app/.netlify/functions/staticman'

# WTF IS THIS THING
# used by <html lang>
lang: id
# used by jekyll-seo-tag (?)
locale: id_ID
# blah
language: id-ID

# used by jekyll-seo-tag
twitter:
  username: akhyarrh

# used by jekyll-seo-tag
social:
  name: Akhyar RH
  links:
    - 'https://twitter.com/akhyarrh'
    - 'https://github.com/akhyarrh'

# site verification
# used by jekyll-seo-tag
webmaster_verifications:
  google: sXiK2vNEKhChWPst96RcH9KxGl4Ib5QbR02dPWIVEts
  bing:   E9A1908DCAA52A63BF7B5F67DB05745D
  alexa:  gXuVtj4bXDWiVB_ihCJijNBQNj8
#  yandex: 1234
#  baidu: 1234
#  facebook: 1234

# not used currently
#naver_site_verification  : 6317134cb9bef4388b660148341705f37c442045

permalink: /:title/

#paginate: 10
#paginate_path: "/page:num/"

show_drafts: false
future:      false
unpublished: false

include:
  - .well-known
  - _headers
  - _redirects

# Hey jekyll, dont include this:
exclude:
  - CNAME
  - Gemfile*
  - LICENSE
  - Makefile
  - Rakefile
  - netlify.toml
  - node_modules
  - vendor
  - staticman.yml
  - package.json
  - package-lock.json
  - jampack.config.mjs

sass:
  style: expanded
  sourcemap: development
  verbose: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# https://help.github.com/articles/configuring-jekyll-plugins/#default-plugins
plugins:
  - jekyll-remote-theme
#  - jekyll-redirect-from
#  - jekyll-github-metadata
  - jekyll-commonmark-ghpages
#  - jekyll-gist
  - jekyll-mentions
  - jekyll-relative-links
  - jemoji
  - jekyll-target-blank
#  - jekyll-og-image
#  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

markdown: CommonMarkGhPages

commonmark:
  options: [SMART, FOOTNOTES, UNSAFE]
  extensions: [table, strikethrough, autolink]

jekyll-mentions: 'https://twitter.com'

# jekyll-og image
#og_image:
  #verbose: true
  #domain: 'akhyar.js.org'
  #canvas:
    #background_color: "#333333"
  #header:
    #color: "#ffffff"
  #content:
    #font_family: 'Georgia, Regular'
    #color: "#ffffff"
  #border_bottom:
    #width: 50

# Cloudflare Turnstile
# Only used on contact page
turnstile:
  site-key: 0x4AAAAAAAxOnZWU9yDH27rf
