name = "akhyarrh-blog"
type = "webpack"
account_id = "" # Fill in your account ID
workers_dev = true
route = "akhyar.js.org/*"
zone_id = "" # Fill in your zone ID

[site]
bucket = "_site" # Jekyll's default output directory
entry-point = "workers-site"

[build]
command = "bundle exec jekyll build"
upload.format = "service-worker"

[build.upload]
format = "service-worker"