name: Build and Deploy to master branch

on:
  push:
    branches:
      - source
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'ruby'
          bundler-cache: true
          
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libvips

      - run: bundle exec jekyll build

      - run: npx @divriots/jampack ./_site

      - uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./_site
          cname: akhyar.js.org
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
          exclude_assets: '.github,assets/css/*.map,assets/js/_main.js,assets/js/lunr/lunr.js,assets/js/lunr/lunr-gr.js,assets/js/plugins/**/*,assets/js/vendor/**/*'
