name: generate-artifact

on:
  push:
    branches:
      - source
  pull_request:

# Necessary permissions to post comments on PRs
permissions:
  pull-requests: write

jobs:
  build_site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgsl-dev

      - name: Cache Jekyll
        uses: actions/cache@v4
        with:
          path: .jekyll-cache
          key: ${{ runner.os }}-jekyll-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-

      - name: Cache Jampack
        uses: actions/cache@v4
        with:
          path: .jampack
          key: jampack-${{ github.run_id }}
          restore-keys: |
            jampack

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          #cache: 'npm'

      - name: Install Node Dependencies
        run: npm install

      - name: Build and Optimize Site
        run: |
          bundle exec jekyll build --lsi && npx @divriots/jampack _site
        env:
          JEKYLL_ENV: production

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site-${{ github.event_name }}-${{ github.sha }}
          path: _site/
          retention-days: 5

      - name: Comment on PR
        if: github.event_name == 'pull_request' && success()
        uses: actions/github-script@v7
        with:
          script: |
            const run_id = context.runId;
            const repository = context.repo.repo;
            const owner = context.repo.owner;
            const link = `
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: owner,
              repo: repository,
              body: `### ✅ Build Successful! \n\nThe artifact for this PR has been generated. You can download it from the **Artifacts** section at the bottom of the [Workflow Summary page](${link}).`
            })
