name: Test

on:
  schedule:
    - cron: '*/30 * * * *'
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x

    - name: Cache bundled gems
      id: bundler-cache
      uses: actions/cache@preview
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Instal dependencies
      if: steps.bundler-cache.outputs.cache-hit != 'true'
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    
    - name: Build
      run: bundle exec jekyll build --profile
      
    - name: Test
      run: bundle exec htmlproofer ./_site --allow-hash-href --assume-extension --check-favicon --check-html --check-opengraph
